version: ''
refreshRate: ''
wakeUpTick: ''
newDayAt: ''
worldsList: ''
initialTick:
  initialTickNb: ''
  resetOnStartup: ''
  useMySql: 'false'
mySql:
  host: ''
  port: ''
  ssl: ''
  dbPrefix: ''
  database: ''
  table: ''
  username: ''
  password: ''
updateMsgSrc: ''
placeholders:
  PlaceholderAPI: ''
  MVdWPlaceholderAPI: ''
  inChatEnable: ''
  inCommandsEnable: ''
debugMode: ''