version: ''
refreshRate: ''
wakeUpTick: ''
newDayAt: ''
worldsList: ''
initialTick:
  initialTickNb: ''
  resetOnStartup: ''
  useMySql: 'false'
mySql:
  host: ''
  port: ''
  ssl: ''
  dbPrefix: ''
  database: ''
  table: ''
  username: ''
  password: ''
updateMsgSrc: ''
placeholders:
  PlaceholderAPI: ''
  MVdWPlaceholderAPI: ''
  inChatEnable: ''
  inCommandsEnable: ''
debugMode: ''
seasons:
  enabled: false
  preset: TEMPERATE
  year-length-days: 32
  smooth-transition: true
  hemisphere: north
  affected-worlds: []
  custom:
    winter-daylight: 0.33
    summer-daylight: 0.67