name: TimeManager
version: 1.10.2
api-version: 1.13
author: ArVdC
main: net.vdcraft.arvdc.timemanager.MainTM
website: vdcraft.net
description: Set and display actual time and date, define per world speed, synchronize worlds timers, execute commands at time, ...
load: POSTWORLD
softdepend: [Multiverse-Core, Multiworld, MVdWPlaceholderAPI, PlaceholderAPI]
database: false
permissions:
  timemanager.*:
    default: op
    children:
      timemanager.admin:
        default: op
      timemanager.now.*:
        default: false
        children:
          timemanager.now.cmd:
            default: true
          timemanager.now.display:
            default: false
          timemanager.now.world:
            default: false
      timemanager.placeholders:
        default: true
      timemanager.sleep.*:
        default: true
        children:
          timemanager.sleep.allowed:
            default: true
          timemanager.sleep.counted:
            default: true
commands:
  tm:
    permission: timemanager.admin
    usage: |
            Here is the complete list of commands, subcommands and arguments:
            /<command> checkConfig
            /<command> checkSql
            /<command> checkTime [all|server|world]
            /<command> checkUpdate [bukkit|curse|spigot|github]
            /<command> help [cmd] [<subCmd>]
            /<command> now [msg|title|actionbar] [all|player|world] 
            /<command> reload [all|config|lang|cmds]
            /<command> resync [all|world]
            /<command> set date [today|yyyy-mm-dd] [all|world]
            /<command> set debugMode [true|false]
            /<command> set defLang [lg_LG]
            /<command> set duration [00d-00h-00m-00s] [all|world]
            /<command> set durationDay [00d-00h-00m-00s] [all|world]
            /<command> set durationNight [00d-00h-00m-00s] [all|world]
            /<command> set elapsedDays [0 → ∞] [all|world]
            /<command> set firstStartTime [default|previous|start] [all|world]
            /<command> set initialtick [ticks|HH:mm]
            /<command> set multiLang [true|false]
            /<command> set playerOffset [-23999 → 23999] [all|player]
            /<command> set playerTime [ticks|daypart|HH:mm:ss|reset] [all|player]
            /<command> set refreshRate [ticks]
            /<command> set sleep [true|false] [all|world]
            /<command> set speed [0.0 → 20.0] [all|world]
            /<command> set speedDay [0.0 → 20.0] [all|world]
            /<command> set speedNight [0.0 → 20.0] [all|world]
            /<command> set start [ticks|daypart|HH:mm:ss|timeShift] [all|world]
            /<command> set sync [true|false] [all|world]
            /<command> set time [ticks|daypart|HH:mm:ss] [all|world]
            /<command> set update [none|bukkit|curse|spigot|github]
            /<command> set useCmds [true|false]
    aliases:
      - tmanag
      - timemanag
      - tmanager
      - timemanager
    description: Generic TimeManager Admin Command
  now:
    permission: timemanager.now.cmd
    usage: /<command> [<msg|title|actionbar>] [<world>]
    description: Display a world actual time (in mc hours or in ticks) and/or date in the chat.
    aliases:
      - time
      - hour
      - date