name: TimeManager
version: 1.4.2
api-version: 1.16
author: ArVdC
main: net.vdcraft.arvdc.timemanager.MainTM
website: vdc.serveminecraft.net
description: Display actual time (in mc hours or in ticks) in the chat, define the speed and the start time then synchronize worlds timers.
load: POSTWORLD
softdepend: [Multiverse-Core, Multiworld, MVdWPlaceholderAPI, PlaceholderAPI]
database: false
permissions:
  timemanager.*:
    default: op
    children:
      timemanager.admin:
        default: op
      timemanager.now.*:
        default: true
        children:
          timemanager.now.cmd:
            default: true
          timemanager.now.units:
            default: true
          timemanager.now.worlds:
            default: false
commands:
  tm:
    permission: timemanager.admin
    usage: |
            Here is the complete list of commands, subcommands and arguments:
            /<command> checkconfig
            /<command> checksql
            /<command> checktime [all|server|world]
            /<command> checkupdate [bukkit|spigot|github]
            /<command> help [cmd] <subCmd>
            /<command> reload [all|config|lang|cmds]
            /<command> resync [all|world]
            /<command> set date [today|yyyy-mm-dd] [all|world]
            /<command> set debugmode [true|false]
            /<command> set deflang [lg_LG]
            /<command> set elapsedDays [0 → ∞] [all|world]
            /<command> set initialtick [tick|HH:mm]
            /<command> set multilang [true|false]
            /<command> set refreshRate [tick]
            /<command> set sleep [true|false] [all|world]
            /<command> set speed [multiplier] [all|world]
            /<command> set speedDay [multiplier] [all|world]
            /<command> set speedNight [multiplier] [all|world]
            /<command> set start [tick|daypart|HH:mm] [all|world]
            /<command> set sync [true|false] [all|world]
            /<command> set time [tick|daypart|HH:mm] [all|world]
            /<command> set update [none|bukkit|spigot|github]
    aliases:
      - tmanag
      - timemanag
      - tmanager
      - timemanager
    description: Generic TimeManager Admin Command
  now:
    permission: timemanager.now.cmd
    usage: /<command> <units> <world>
    description: Display a world actual time (in mc hours or in ticks) in the chat.
    aliases:
      - time
      - hour
      - date